name: Manual Scrape Trigger

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.GIT_TOKEN }}"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install requests

      - name: Run scraper
        run: |
          echo "Running the scraper script..."
          python scraper.py

      - name: List results directory
        run: |
          echo "Listing the files in the results directory..."
          ls -l results/

      - name: Display file content
        run: |
          echo "Displaying the content of results files..."
          cat results/* || echo "No results found."

      - name: Push results
        run: |
          echo "Configuring Git user..."
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          echo "Adding result files..."
          git add results/*.txt
          echo "Committing result files..."
          git commit -m 'Add scrape results' || echo 'No changes to commit'
          echo "Pushing changes to repository..."
          git push
